// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLPTPMQLNHOM12.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221201164638_Phongban")]
    partial class Phongban
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BTL_PTPMQL_NHOM12.Models.Phongban", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPB");

                    b.ToTable("Phongban");
                });
#pragma warning restore 612, 618
        }
    }
}
