// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLPTPMQLNHOM12.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221201171919_Loaidichvu")]
    partial class Loaidichvu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BTL_PTPMQL_NHOM12.Models.Loaidichvu", b =>
                {
                    b.Property<string>("MaLoaiDV")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLoaiDV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YeuCaudikem")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLoaiDV");

                    b.ToTable("Loaidichvu");
                });

            modelBuilder.Entity("BTL_PTPMQL_NHOM12.Models.Nganhang", b =>
                {
                    b.Property<string>("MaNH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNH");

                    b.ToTable("Nganhang");
                });

            modelBuilder.Entity("BTL_PTPMQL_NHOM12.Models.Phongban", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPB");

                    b.ToTable("Phongban");
                });

            modelBuilder.Entity("BTL_PTPMQL_NHOM12.Models.PhuongThucTT", b =>
                {
                    b.Property<string>("MaPT")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhuongThucthanhToan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPT");

                    b.ToTable("PhuongThucTT");
                });
#pragma warning restore 612, 618
        }
    }
}
